### ISSUE TITLE
Reduce timeout for nginx

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-website#24]
Timeout seems to be 60 seconds, should be reduced to 5 oder 10 seconds.

**Comment by hauptmedia** [comment]
Does not make sense right now because registration emails are beint directly sent by php and this is a blockig call which can take longer than 10 seconds to process. We can change this as soon as we moved email handling into backend

**Comment by skyrun2001** [comment]
Issue Moved to Trello
