### ISSUE TITLE
Seite "Medizinische Schutzausrüstung"

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-website#28]
Es soll eine Unterseite "Medizinische Schutzausrüstung" angelegt werden, auf der wir verschiedene Produkte zur Schutz vor Infektionen vorstellen. Das soll unser Google Ranking verbessern.

# Technische Beschreibung
- Unterseite anlegen
- Unterseite im Footer verlinken
- Mit Marketing das Layout der Seite Besprechen und Texte anfertigen lassen

**Comment by skyrun2001** [comment]
- [ ] Lizenzfrei Bilder

- [ ] Website Design erstellen

- [ ] Texte vom Marketing bekommen

**Comment by skyrun2001** [comment]
Issue Moved to Trello
