### ISSUE TITLE
Internationationalisierung

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-website#43]
Die Seite soll übersetzbar werden.

**Comment by skyrun2001** [comment]
Automatisch oder manuell übersetzt werden?

**Comment by roman-1983** [comment]
Ich integriere gerade das hier:
https://symfony.com/doc/4.4/translation.html#installation

**Comment by roman-1983** [comment]
Branch needs rebase

**Comment by scriptibus** [comment]
Wird gerade im Branch `feature/translations` erstellt. Die Übersetzung selber wird über Slack organisiert.

**Comment by scriptibus** [comment]
Übersetzung ist im Gange, dauert aber noch an

**Comment by skyrun2001** [comment]
Issue Moved to Trello
