### ISSUE TITLE
Verwaltung Presse-Meldungen

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-website#61]
Es soll möglich sein, dass man die Pressemeldungen über die Datenbank pflegen kann.

## Technische Beschreibung
- Der Zugriff soll geschützt sein
- Es soll mindestens folgende Eingabefelder geben
-- Datum
-- Url
-- Kurze Beschreibung
-- Bildupload für Logo
-- Highlight ja/nein
-- Sprache

**Comment by skyrun2001** [comment]
Issue Moved to Trello
