### ISSUE TITLE
Partner-Verwaltung

### ISSUE THREAD

**Issue by roman-1983** [remedyMatch/rm-website#62]
Es soll möglich sein, dass man die Partner über die Datenbank pflegen kann.

## Technische Beschreibung
- Der Zugriff soll geschützt sein
- Es soll mindestens folgende Eingabefelder geben
-- Datum
-- Url
-- Partner
-- Kurze Beschreibung
-- Bildupload für Logo

**Comment by skyrun2001** [comment]
Issue Moved to Trello
