### ISSUE TITLE
Es werden Teilweise Mails nicht versendet

### ISSUE THREAD

**Issue by skyrun2001** [remedyMatch/rm-website#71]
Manchmal gehen Emails verloren. Die ist im Moment nicht reproduzierbar. Bitte einmal nachprüfen und eventuell fixen.

**Comment by scriptibus** [comment]
Hier könnte eventuell die Umsetzung von #68 bei der Fehlersuche helfen

**Comment by skyrun2001** [comment]
Vermutlich liegt es am lokalen Testen, dass wir denken es werden keine Emails versendet. Der Slack Bot gibt die Mitteilung aber es werden keine Emails versendet, wahrscheinlich liegt das am lokalen Testen mit dem Slack Token in der .env.

Ich nehme das Issue erstmal vom MVP

**Comment by skyrun2001** [comment]
Issue Moved to Trello
