### ISSUE TITLE
Wepack integrieren

### ISSUE THREAD

**Issue by scriptibus** [remedyMatch/rm-website#86]
Wenn sich eine der JS oder CSS Dateien verändert, liegt sie bei den Usern ggf. schon im Browser Cache vor und das Update wird somit nicht geladen. 
Daher wird aktuell mittels Environment Variable ein GET Parameter an das Asset angehängt. Ändert man diese Variable, gibt es entsprechend einen neuen Dateinamen und Browser laden die Datei erneut herunter.

Mit Webpack würde die Dateien automatisert generiert und nach ihrem Inhalts-Hash benannt. Dadurch lassen sich auch nur einzelne Dateien invalidieren, wo es aktuell nur möglich ist, alles zu invalidieren. Außerdem wäre webpack in der Lage bestimmte Schritte wie Browser Komptibilität und Minifiyng durchzuführen.

Zu beachten ist, das bestimmte Logos aktuell von anderen Tool unter festen Pfaden verwendet werden. Diese liegen aktuell schon außerhalb des Assets Ordners.

**Comment by skyrun2001** [comment]
Done in #92
