### ISSUE TITLE
"Wer kann Spender werden Section" erstellen

### ISSUE THREAD

**Issue by scriptibus** [remedyMatch/rm-website#88]
Section ist auf der Startseite über about us einzufügen.
<img width="1372" alt="Screenshot 2020-04-16 at 00 23 37" src="https://user-images.githubusercontent.com/17888909/79395139-4d20ff80-7f79-11ea-8aae-7fe59b5f52cb.png">

**Comment by scriptibus** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/VqHSpZ4s/1-test)

**Comment by skyrun2001** [comment]
#91
